import { useEffect, useState } from "react";
import { ScreenMessageIA } from "../ScreenMessageIA/ScreenMessageIA";
import { SpinnerLoader } from "../SpinnerLoader/SpinnerLoader";
import './ScreenIA.css';
import type { ScreenIAProps } from "./ScreenIATypes";

/**
* Name           : ScreenIA
* Purpose        : React component that displays AI-generated messages and shows a loading spinner while waiting for a response.
* Parameters     :
*    - responseMessage (string) : The latest message generated by the AI, which will be added to the message list.
*    - loading (boolean)        : Indicates whether a loading spinner should be displayed.
* Returns        : JSX.Element - Visual component that renders all received messages along with a loading indicator if active.
*/
export const ScreenIA = ({ responseMessage, loading }: ScreenIAProps) => {
  const [messages, setMessages] = useState<string[]>([]);

  useEffect(() => {
    if (responseMessage) {
      setMessages((prevMessages) => [...prevMessages, responseMessage]);
    }
  }, [responseMessage]);

  return (
    <div className="screen-ia">
      <ScreenMessageIA messages={messages} />
      {loading && (
        <div className="screen-ia__loading">
          <SpinnerLoader />
        </div>
      )}
    </div>
  );
}
